networks:
  composition_network:
    external: true

services:
  composition:
    build:
      context: .
      dockerfile: composition/Dockerfile
    networks:
      - composition_network
    deploy:
      replicas: 3

  score:
    container_name: score
    build:
      context: .
      dockerfile: score/Dockerfile
    networks:
      - composition_network

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: auth/Dockerfile
    ports:
      - "50051:50051"
    networks:
      - composition_network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - composition_network